#!/bin/bash
#
#
# Help command


_check_eligible_options() {
    echo ${@}
    echo ${_eligibleOptions}
    _found=0
    for _elopt in $_eligibleOptions; do
        echo $_elopt
        echo "1111"
        case $1 in
            $_elopt)
                _found=1
                break;
                ;;
        esac
    done
    if [ $_found -eq 0 ]; then
        _die "Option $1 is not supported. Try help for more information."
    fi
}


_confirm_the_command() {
    while true; do
        read -p "Proceed ? [y/n] : " key
        case $key in
            [Yy]*) break;;
            [Nn]*) return 0;;
        esac
    done
}


_invoke_command() {
    command_str="$@"
    command_len=${#command_str}
    invoking_str="Invoking: "
    invoking_len=${#invoking_str}
    len=$(expr $command_len + $invoking_len)

    if [ $len -gt $(tput cols) ]; then
        line_len=$(tput cols)
    else
        line_len=$len
    fi

    printf "%*s\n" $line_len | tr " " "."
    printf "Invoking: %s\n" "$command_str"
    printf "%*s\n" $line_len | tr " " "."

    eval "$command_str"
}


_die() {
    echo $@
    return 1
}
